# Generated by Django 3.1 on 2020-08-31 12:40

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200831_1240'),
        ('users', '0002_auto_20200808_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favs',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='favs', to='rooms.Room'),
        ),
    ]
