# Generated by Django 3.1 on 2020-08-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200831_1240'),
        ('users', '0003_auto_20200831_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(blank=True, related_name='favs', to='rooms.Room'),
        ),
    ]
