# Generated by Django 3.1 on 2020-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200831_1240'),
        ('users', '0004_auto_20200831_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(related_name='favs', to='rooms.Room'),
        ),
    ]
